# Generated by Django 3.2.4 on 2021-06-24 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ref', models.URLField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='usernet',
            old_name='github',
            new_name='social',
        ),
        migrations.CreateModel(
            name='UsersMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='profiles.genre')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='name_users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernet',
            name='users_media',
            field=models.ManyToManyField(related_name='users', to='profiles.UsersMedia'),
        ),
    ]
