# Generated by Django 3.2.4 on 2021-06-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210624_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='users_media',
        ),
    ]
